/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spanclient
// ListCollectionResponse Collection list. The list contains all the collections you have access to.
type ListCollectionResponse struct {
	Collections []Collection `json:"collections,omitempty"`
}
