/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// DumpedCollection struct for DumpedCollection
type DumpedCollection struct {
	Collection Collection `json:"collection,omitempty"`
	Devices []DumpedDevice `json:"devices,omitempty"`
	Outputs []Output `json:"outputs,omitempty"`
}
