/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spanclient
// OutputLogEntry struct for OutputLogEntry
type OutputLogEntry struct {
	Time string `json:"time,omitempty"`
	Message string `json:"message,omitempty"`
	Repeated int32 `json:"repeated,omitempty"`
}
