/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spanclient
// Member struct for Member
type Member struct {
	UserId string `json:"userId,omitempty"`
	TeamId string `json:"teamId,omitempty"`
	Role string `json:"role,omitempty"`
	Name string `json:"name,omitempty"`
	Email string `json:"email,omitempty"`
	Phone string `json:"phone,omitempty"`
	AvatarUrl string `json:"avatarUrl,omitempty"`
	ConnectId string `json:"connectId,omitempty"`
	GitHubLogin string `json:"gitHubLogin,omitempty"`
	VerifiedEmail bool `json:"verifiedEmail,omitempty"`
	VerifiedPhone bool `json:"verifiedPhone,omitempty"`
	AuthType string `json:"authType,omitempty"`
}
