/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// FieldMask struct for FieldMask
type FieldMask struct {
	Imsi bool `json:"imsi,omitempty"`
	Imei bool `json:"imei,omitempty"`
	Msisdn bool `json:"msisdn,omitempty"`
	Location bool `json:"location,omitempty"`
}
