/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// CollectionFirmwareFirmwareManagement The firmware management settings for a collection can either be \"disabled\", ie there is no firmware management for this collection, \"collection\"; devices are managed through the settings on the collection or \"device\" where each device is configured individual.
type CollectionFirmwareFirmwareManagement string

// List of CollectionFirmwareFirmwareManagement
const (
	UNSPECIFIED CollectionFirmwareFirmwareManagement = "unspecified"
	DISABLED CollectionFirmwareFirmwareManagement = "disabled"
	COLLECTION CollectionFirmwareFirmwareManagement = "collection"
	DEVICE CollectionFirmwareFirmwareManagement = "device"
)
