/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spanclient
// Token struct for Token
type Token struct {
	// The resource of the token.  The token applies to the specified resource and any resources below this so the resource `/` applies to the root resource and any resource below the root resource. In the same manner `/collections` will apply to all collectins while `/collections/{id}` will apply to that particular collection.
	Resource string `json:"resource,omitempty"`
	// Write flag for token.  If this is set to `true` the token can be used for write operations in the API such as POST, DELETE and PATCH.
	Write bool `json:"write,omitempty"`
	// Use this in the `X-API-Token` header when using the API.
	Token string `json:"token,omitempty"`
	// Tags for the token.
	Tags map[string]string `json:"tags,omitempty"`
}
