/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spanclient
// SystemInfoResponse struct for SystemInfoResponse
type SystemInfoResponse struct {
	Version string `json:"version,omitempty"`
	BuildDate string `json:"buildDate,omitempty"`
	ReleaseName string `json:"releaseName,omitempty"`
	DefaultFieldMask FieldMask `json:"defaultFieldMask,omitempty"`
	ForcedFieldMask FieldMask `json:"forcedFieldMask,omitempty"`
}
