/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spanclient
// OutputConfig Output configuration.
type OutputConfig struct {
	Url string `json:"url,omitempty"`
	BasicAuthUser string `json:"basicAuthUser,omitempty"`
	BasicAuthPass string `json:"basicAuthPass,omitempty"`
	CustomHeaderName string `json:"customHeaderName,omitempty"`
	CustomHeaderValue string `json:"customHeaderValue,omitempty"`
	Host string `json:"host,omitempty"`
	Port int32 `json:"port,omitempty"`
	Key string `json:"key,omitempty"`
	EventName string `json:"eventName,omitempty"`
	AsIsPayload bool `json:"asIsPayload,omitempty"`
	Endpoint string `json:"endpoint,omitempty"`
	// MQTT configuration: Disable certificate checks. Default is off.
	DisableCertCheck bool `json:"disableCertCheck,omitempty"`
	Username string `json:"username,omitempty"`
	Password string `json:"password,omitempty"`
	ClientId string `json:"clientId,omitempty"`
	TopicName string `json:"topicName,omitempty"`
}
