/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 4.0.11 ambulant-epsie
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// NetworkMetadata Network metadata for devices.
type NetworkMetadata struct {
	// Allocated IP address.
	AllocatedIp string `json:"allocatedIp,omitempty"`
	AllocatedAt string `json:"allocatedAt,omitempty"`
	// Cell ID for device. This might not be set, depending on the provider in use.
	CellId string `json:"cellId,omitempty"`
}
