/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 4.0.8 freckled-fawn
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// RuntimeStreamError struct for RuntimeStreamError
type RuntimeStreamError struct {
	GrpcCode int32 `json:"grpcCode,omitempty"`
	HttpCode int32 `json:"httpCode,omitempty"`
	Message string `json:"message,omitempty"`
	HttpStatus string `json:"httpStatus,omitempty"`
	Details []ProtobufAny `json:"details,omitempty"`
}
