/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spanclient
// CollectionFirmwareFirmwareManagement The firmware management settings for a collection can either be \"disabled\", ie there is no firmware management for this collection, \"collection\"; devices are managed through the settings on the collection or \"device\" where each device is configured individual.
type CollectionFirmwareFirmwareManagement string

// List of CollectionFirmwareFirmwareManagement
const (
	UNSPECIFIED CollectionFirmwareFirmwareManagement = "unspecified"
	DISABLED CollectionFirmwareFirmwareManagement = "disabled"
	COLLECTION CollectionFirmwareFirmwareManagement = "collection"
	DEVICE CollectionFirmwareFirmwareManagement = "device"
)
