/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// ListCollectionResponse Collection list. The list contains all the collections you have access to.
type ListCollectionResponse struct {
	Collections []Collection `json:"collections,omitempty"`
}
