/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// OutputLogEntry struct for OutputLogEntry
type OutputLogEntry struct {
	Time string `json:"time,omitempty"`
	Message string `json:"message,omitempty"`
	Repeated int32 `json:"repeated,omitempty"`
}
