/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 4.0.8 freckled-fawn
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// CreateFirmwareRequest struct for CreateFirmwareRequest
type CreateFirmwareRequest struct {
	CollectionId string `json:"collectionId,omitempty"`
	Image string `json:"image,omitempty"`
	Version string `json:"version,omitempty"`
	Filename string `json:"filename,omitempty"`
	Tags map[string]string `json:"tags,omitempty"`
}
