/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spanclient
// TeamList struct for TeamList
type TeamList struct {
	Teams []Team `json:"teams,omitempty"`
}
