/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spanclient
// OutputDataMessageOutputMessageType the model 'OutputDataMessageOutputMessageType'
type OutputDataMessageOutputMessageType string

// List of OutputDataMessageOutputMessageType
const (
	UNKNOWN OutputDataMessageOutputMessageType = "unknown"
	KEEPALIVE OutputDataMessageOutputMessageType = "keepalive"
	DATA OutputDataMessageOutputMessageType = "data"
)
