/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// Firmware Firmware images aren't served back out through the API, only the metadata.
type Firmware struct {
	ImageId string `json:"imageId,omitempty"`
	// Make sure that the firmware image reports this version. If the version reported by this image is different the FOTA process won't be reported as successful since the device will report a version different from this.
	Version string `json:"version,omitempty"`
	// This is just for internal house keeping, making it potentially easier to identify the firmware image.
	Filename string `json:"filename,omitempty"`
	// To ensure each image is unique the SHA-256 hash for all images in a collection must be unqique
	Sha256 string `json:"sha256,omitempty"`
	Length int32 `json:"length,omitempty"`
	// Collection ID for the collection owning the firmware image.
	CollectionId string `json:"collectionId,omitempty"`
	Created string `json:"created,omitempty"`
	// Tags for firmware image.
	Tags map[string]string `json:"tags,omitempty"`
}
