/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spanclient
// RuntimeStreamError struct for RuntimeStreamError
type RuntimeStreamError struct {
	GrpcCode int32 `json:"grpcCode,omitempty"`
	HttpCode int32 `json:"httpCode,omitempty"`
	Message string `json:"message,omitempty"`
	HttpStatus string `json:"httpStatus,omitempty"`
	Details []ProtobufAny `json:"details,omitempty"`
}
