/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// CoApMetadata struct for CoApMetadata
type CoApMetadata struct {
	Code string `json:"code,omitempty"`
	Path string `json:"path,omitempty"`
}
