/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 4.0.8 freckled-fawn
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// ListDevicesResponse struct for ListDevicesResponse
type ListDevicesResponse struct {
	Devices []Device `json:"devices,omitempty"`
}
