/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// OutputDataMessage The output data message contains payload plus metadata for a payload received from a device.
type OutputDataMessage struct {
	Type OutputDataMessageOutputMessageType `json:"type,omitempty"`
	Device Device `json:"device,omitempty"`
	Payload string `json:"payload,omitempty"`
	// Received time for message. Value is ms since epoch.
	Received string `json:"received,omitempty"`
	Transport string `json:"transport,omitempty"`
	UdpMetaData UdpMetadata `json:"udpMetaData,omitempty"`
	CoapMetaData CoApMetadata `json:"coapMetaData,omitempty"`
	MessageId string `json:"messageId,omitempty"`
}
