/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spanclient
// InviteList List of active invites. Onece an invite has been redeemed it will be removed automatically. An administrator of the team can delete unused invites.
type InviteList struct {
	Invites []Invite `json:"invites,omitempty"`
}
