/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 4.1.3 factual-kahlil
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// UpdateDeviceRequest struct for UpdateDeviceRequest
type UpdateDeviceRequest struct {
	ExistingCollectionId string `json:"existingCollectionId,omitempty"`
	DeviceId string `json:"deviceId,omitempty"`
	// The collection id for the device. This field is optional and can be omitted if the collection id isn't changed. When changing to a new collection you must be an owner of the other collection, ie an administrator of the team that owns the new collection.
	CollectionId string `json:"collectionId,omitempty"`
	// The IMSI is the unique ID for the (e|nu|whatever)SIM card on your device. This is the primary identifier for your device on the network.
	Imsi string `json:"imsi,omitempty"`
	// The IMEI number is the unique ID for your hardware as seen by the network. Obviously you might have a completely different view on things.
	Imei string `json:"imei,omitempty"`
	// Tags are metadata for the device that you can set. These are just strings.
	Tags map[string]string `json:"tags,omitempty"`
	Firmware FirmwareMetadata `json:"firmware,omitempty"`
}
