/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// ListDataResponse struct for ListDataResponse
type ListDataResponse struct {
	Data []OutputDataMessage `json:"data,omitempty"`
}
