/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// InviteRequest struct for InviteRequest
type InviteRequest struct {
	TeamId string `json:"teamId,omitempty"`
	// The invite code.
	Code string `json:"code,omitempty"`
}
