/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spanclient
// AcceptInviteRequest struct for AcceptInviteRequest
type AcceptInviteRequest struct {
	// The invite code to use.
	Code string `json:"code,omitempty"`
}
