/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spanclient
// CreateFirmwareRequest struct for CreateFirmwareRequest
type CreateFirmwareRequest struct {
	CollectionId string `json:"collectionId,omitempty"`
	Image string `json:"image,omitempty"`
	Version string `json:"version,omitempty"`
	Filename string `json:"filename,omitempty"`
	Tags map[string]string `json:"tags,omitempty"`
}
