/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// UserProfile Your user profile. You can change the contents of the user profile via the log in service you are using.
type UserProfile struct {
	Email string `json:"email,omitempty"`
	Phone string `json:"phone,omitempty"`
	VerifiedEmail bool `json:"verifiedEmail,omitempty"`
	VerifiedPhone bool `json:"verifiedPhone,omitempty"`
	AvatarUrl string `json:"avatarUrl,omitempty"`
	Name string `json:"name,omitempty"`
	ProfileUrl string `json:"profileUrl,omitempty"`
	GithubLogin string `json:"githubLogin,omitempty"`
	Provider string `json:"provider,omitempty"`
	LogoutUrl string `json:"logoutUrl,omitempty"`
	ConnectId string `json:"connectId,omitempty"`
}
