/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 4.0.11 ambulant-epsie
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// ListFirmwareResponse struct for ListFirmwareResponse
type ListFirmwareResponse struct {
	Images []Firmware `json:"images,omitempty"`
}
