/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 4.0.8 freckled-fawn
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// OutputStatus struct for OutputStatus
type OutputStatus struct {
	CollectionId string `json:"collectionId,omitempty"`
	OutputId string `json:"outputId,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	ErrorCount int32 `json:"errorCount,omitempty"`
	Forwarded int32 `json:"forwarded,omitempty"`
	Received int32 `json:"received,omitempty"`
	Retransmits int32 `json:"retransmits,omitempty"`
}
