/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spanclient
// OutputDataMessage The output data message contains payload plus metadata for a payload received from a device.
type OutputDataMessage struct {
	Type OutputDataMessageOutputMessageType `json:"type,omitempty"`
	Device Device `json:"device,omitempty"`
	Payload string `json:"payload,omitempty"`
	Received string `json:"received,omitempty"`
	Transport string `json:"transport,omitempty"`
	UdpMetaData UdpMetadata `json:"udpMetaData,omitempty"`
	CoapMetaData CoApMetadata `json:"coapMetaData,omitempty"`
}
