/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spanclient
// UdpMetadata struct for UdpMetadata
type UdpMetadata struct {
	LocalPort int32 `json:"localPort,omitempty"`
	RemotePort int32 `json:"remotePort,omitempty"`
}
