/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 4.0.8 freckled-fawn
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// OutputDataMessageOutputMessageType the model 'OutputDataMessageOutputMessageType'
type OutputDataMessageOutputMessageType string

// List of OutputDataMessageOutputMessageType
const (
	UNKNOWN OutputDataMessageOutputMessageType = "unknown"
	KEEPALIVE OutputDataMessageOutputMessageType = "keepalive"
	DATA OutputDataMessageOutputMessageType = "data"
)
