/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spanclient
// FirmwareUsageResponse struct for FirmwareUsageResponse
type FirmwareUsageResponse struct {
	ImageId string `json:"imageId,omitempty"`
	Targeted []string `json:"targeted,omitempty"`
	Current []string `json:"current,omitempty"`
}
