/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * API version: 3.0.0
 * Contact: dev@lab5e.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spanclient
// SendMessageRequest struct for SendMessageRequest
type SendMessageRequest struct {
	CollectionId string `json:"collectionId,omitempty"`
	DeviceId string `json:"deviceId,omitempty"`
	Port int32 `json:"port,omitempty"`
	Payload string `json:"payload,omitempty"`
	// Valid transports are \"udp\", \"coap\", \"coap-pull\", \"udp-pull\", \"coap-push\", \"udp-push\". \"udp\" is equivalent to \"udp-push\" and \"coap\" is equivalent to \"coap-push\". Push messages are sent unsolicited to the device wheil pull messages are sent whenever the device wither sends data upstream (for UDP) or does a CoAP request to the CoAP service in span.
	Transport string `json:"transport,omitempty"`
	CoapPath string `json:"coapPath,omitempty"`
}
